### ISSUE TITLE
Allow `init` from `(Alg, f, u0, tspan, p)`

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/DiffEqBase.jl#125]
I wanted to do a PR that allows `init` to also start from something more minimal, like e.g. `(Alg, f, u0, tspan, p)`. 

I see from here:
```
function init(prob::DEProblem,args...;kwargs...)
  _prob = get_concrete_problem(prob,kwargs)
  if haskey(kwargs,:alg) && (isempty(args) || args[1] === nothing)
    __init(_prob,kwargs[:alg],args...;kwargs...)
  else
    __init(_prob,args...;kwargs...)
  end
end
```
that `init` actually makes a DEproblem _one more time_ and then calls `__init`. Is it safe to assume that `__init` is defined on the Algorithm level?

In general, is it possible to do what I suggest? It would totally skip creating 2 ODEProblems which as far as I can tell is the minimum amount that are created, before making an integrator.

To answer the immediate response of "But making ODEproblems is very cheap", yes I know, but for me code clarity is also a big concern. If we can make this feature happen, it would reduce some source code of **DynamicalSystems.jl** by 30% or so.

By the way it is totally fine for me to do a PR that does this, if it is accepted, provided I have some minimal guidance since I've never devved DiffEq.

**Comment by ChrisRackauckas** [comment]
`init(Alg, f, u0, tspan, p)` doesn't work in many cases so it would require a lot of special casing, and that special casing is exactly the problem types. Why not just call `__init` instead? Or just add fast paths to `init` and `solve` that if you have concrete `u0` and `tspan` then it just passes on the problem?

**Comment by Datseris** [comment]
> Or just add fast paths to init and solve that if you have concrete u0 and tspan then it just passes on the problem?

Yeah this seems like the best approach

**Comment by ChrisRackauckas** [comment]
If that's the interface you want to show, that might be one of the easiest ways to do it.

**Comment by Datseris** [comment]
The exported API looks like this:

---

    parallel_integrator(ds::DynamicalSystem, states; kwargs...)
Return an integrator object that can be used to evolve many `states` of
a system in parallel at the *exact same times*, using `step!(integ [, Δt])`.

`states` are expected as vectors of vectors.

## Keyword Arguments
* `u0, t0` : Optional different initial state and time.
* `diff_eq_kwargs` : see [`trajectory`](@ref).
* All other (extra) keywords are passed to `init` of DiffEq, including a `callback`.
  The solving algorithm must still be specified via `diff_eq_kwargs`.

---

In the above case `tfinal` is for internal use. I feel it is very weird to have both `diff_eq_kwargs` and `kwargs...`. Maybe I can safely remove the first and always have `kwargs...` propagating to `init`.

**Comment by Datseris** [comment]
Okay, I have reworked it a bit. Now I do:
```
function tangent_integrator(ds::CDS{IIP}, Q0::AbstractMatrix;
    u0 = ds.u0, diffeq...) where {IIP}

    t0 = ds.t0
    Q = safe_matrix_type(Val{IIP}(), Q0)
    u = safe_state_type(Val{IIP}(), u0)

    k = size(Q)[2]
    k > dimension(ds) && throw(ArgumentError(
    "It is not possible to evolve more tangent vectors than the system's dimension!"
    ))

    tangentf = create_tangent(ds.f, ds.jacobian, ds.J, Val{IIP}(), Val{k}())
    tanprob = ODEProblem{IIP}(tangentf, hcat(u, Q), (t0, typeof(t0)(Inf)), ds.p)

    solver = _get_solver(diffeq)
    return  __init(tanprob, solver; DEFAULT_DIFFEQ_KWARGS...,
                   save_everystep = false, diffeq...)
end
```
I am happy with it, since it allows different default values for e.g. `abstol`, contained in `DEFAULT_DIFFEQ_KWARGS` and keeps everything as clean as possible, and uses `__init` as well.
