### ISSUE TITLE
Don't overwrite `Base.iterate` method

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiffEq/DiffEqBase.jl#133]
This method:

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/eccb41745f992995bd647fb72d14debfb45ec657/src/integrator_interface.jl#L219

seems a little too generic :slightly_smiling_face:. It's causing

```
WARNING: Method definition iterate(Any) in module Base at essentials.jl:853 overwritten in module DiffEqBase at /home/twan/.julia/packages/DiffEqBase/uu9hR/src/integrator_interface.jl:220.
```

for me now.

**Comment by tkoolen** [comment]
Ah, dup of #131.

**Comment by ChrisRackauckas** [comment]
oh hehe
