### ISSUE TITLE
Releasing DiffEqBase > v4.21.0 for Julia 0.7?

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/DiffEqBase.jl#135]
Thanks for backporting the iterator fix to 0.7!  But the version number it gets is v4.20.3 https://github.com/JuliaDiffEq/DiffEqBase.jl/releases/tag/v4.20.3 which is less than v4.21.0 which is already released.  Is it intentional?  Shouldn't it be something > v4.21.0?

If you just simply do `pkg> add DiffEqBase` then you get `v4.21.0`.

```console
$ mkdir diffeqtest
$ cd diffeqtest
$ julia-0.7.0

(v0.7) pkg> activate .

(diffeqtest) pkg> add DiffEqBase
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `Project.toml`
  [2b5f629d] + DiffEqBase v4.21.0
  Updating `Manifest.toml`
  ...
```

Or maybe you are planning to bound the version numbers in downstream packages?

**Comment by ChrisRackauckas** [comment]
That was just a mistake. The issue was that v4.21.0 was supposed to be tagged as v1.0 only which screwed everything up since it was a buggy release...
