### ISSUE TITLE
Requires does not cause method to add dispatch

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#142]
```julia
handle_distribution_u0(_u0) = _u0
@require Distributions="31c24e10-a181-5473-b8eb-7969acd0382f" begin
  handle_distribution_u0(_u0::Distributions.Sampleable) = rand(_u0)
end
```

is done to sample the distributions when applicable. However, it doesn't seem like Requires actually makes the calling function recompile after Distributions.jl is added to main. I am not sure how to reproduce this though since

```julia
module Tester
  using Requires
  f(x) = x
  @require Distributions="31c24e10-a181-5473-b8eb-7969acd0382f" begin
    f(x::Float64) = 2x
  end
  export f
end
using Main.Tester

f(2.0)
using Distributions
f(2.0)
```

works correctly. @MikeInnes do you know about this?

**Comment by MikeInnes** [comment]
The require block now needs to explicitly be run at init time. You can do `@init @require ...` to get the old behaviour.
