### ISSUE TITLE
remake destruction

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#145]
It seems we didn't have good enough tests on remake.

https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/417976252#L846
https://travis-ci.org/JuliaDiffEq/StochasticDiffEq.jl/jobs/417966073#L835

I am not sure what this is.

**Comment by ChrisRackauckas** [comment]
Maybe it's the form with no keyword arguments?

**Comment by ChrisRackauckas** [comment]
It looks like we passed all of the tests on the odd cases, but broke the standard one which was missing tests.

**Comment by tkf** [comment]
Oops. I opened a dup in #146 (which explains why it breaks). I'll fix it.
