### ISSUE TITLE
SteadyStateProblem does not work with solve() calls including additional arguments.

### ISSUE THREAD

**Issue by jgoodson** [JuliaDiffEq/DiffEqBase.jl#155]
`SteadyStateProblem` does not have a `tspan` field. A call to `solve(prob::DEProblem,args...;kwargs...)` with a `SteadyStateProblem` works with no additional args/kwargs.

If the call to `solve()` specifies an algorithm, the function tests for whether the algorithm is adaptive and includes a call to `adaptive_warn()` that uses `_prob.tspan` which is not present for `SteadyStateProblem`.

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/f76d9d82a0f3451dd9d9d9222f266934f07ab603/src/solve.jl#L20-L33

```
ssp = SteadyStateProblem(bf, u0, [1e6 1e6])
sol = solve(op, SSRootfind())

#type SteadyStateProblem has no field tspan
```
```
op = SteadyStateProblem(bf, u0, [1e6, kds...])
sol = solve(op)

#u: 5-element Array{Float64,1}: 8.294661054387688e-7  6.204569470137357e-7  5.109329207617541e-19 5.691905496641993e-8  3.5517587093636394e-8
```

**Comment by ChrisRackauckas** [comment]
Took longer than it should've, but this is now fixed on master via https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/c0a68a7797ae18adf670790c2b4371b6b744b29b and will be tagged very soon.
