### ISSUE TITLE
logspace in 1.0

### ISSUE THREAD

**Issue by tungli** [JuliaDiffEq/DiffEqBase.jl#159]
`logspace()` was destroyed in favor of `base .^range(...)`

I encountered an `ERROR: UndefVarError: logspace not defined` while using `plot` from Plots.jl, [here](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solutions/solution_interface.jl), line 85.

```julia
  # determine type of spacing for plott
  tscale = get(plotattributes, :xscale, :identity)
  densetspacer = if tscale in [:ln, :log10, :log2]
    (start, stop, n) -> logspace(log10(start), log10(stop), n)
  else
    (start, stop, n) -> range(start;stop=stop,length=n)
  end
```

**Comment by YingboMa** [comment]
Thanks for reporting this issue! Do you mind to submit a PR to fix this?

**Comment by tungli** [comment]
Created #160. This is my first ever pull request. Is it done correctly?

**Comment by YingboMa** [comment]
Thank you, and welcome to open source! Yes, it looks good. I will review it soon.

**Comment by YingboMa** [comment]
#160
