### ISSUE TITLE
DEFAULT_LINSOLVE fails with sparse and banded matrices

### ISSUE THREAD

**Issue by AleMorales** [JuliaDiffEq/DiffEqBase.jl#178]
As `DEFAULT_LINSOLVE` is set to `LinSolveFactorize(lu!)` this will fail if a `BandedMatrix` or `SparseMatrixCSC` is passed to `jac_prototype` because `lu!` is not defined for these types of matrices (at least in Julia 1.0). Of course, passing `LinSolveFactorize(lu)` or `LinSolveFactorize(factorize)` to the `linsolve` argument will work. 

The current situation is very confusing for newbies. I don't know if the best approach is to (i) provide a default that works with the widest range of matrices (e.g. `LinSolveFactorize(factorize)`) and leave in-place versions as a performance tweak for matrices that support it or (ii) to document that if sparse or banded matrices are used, a different factorization function must be passed to `linsolve`.

**Comment by ChrisRackauckas** [comment]
I think we should make the default as good as possible, and abandon having it just be a single `LinSolveFactorize`. I.e. it should change behavior depending on the matrix input type, and know when to `lu` vs `lu!`. I planned on getting to it but just never did.
