### ISSUE TITLE
Change `affect_neg!` keyword arg to instead be a different constructor

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#18]
While it seems odd to get rid of `!` on a mutating function, @ccontrer 's example brings up a big issue:

```
callback = ContinuousCallback(condtion,affect_bounce!,rootfind,save_positions,affect_neg! = affect_negative!)
```

That works.

```
callback = ContinuousCallback(condtion,affect_bounce!,rootfind,save_positions,affect_neg!=affect_negative!)
```

That errors. See the difference? Julia parses `affect_neg!=affect_negative!` as `affect_neg` `!=` `affect_negative!`, and errors. That's not nice behavior, and so I think it might be best to just take off the `!`.

**Comment by ccontrer** [comment]
Right! I thought about that. Well, it's only a keyword, isn't it? The function itself will still be mutating function.

**Comment by ChrisRackauckas** [comment]
Yeah, but the name should probably be consistent. If the keyword arg is `affect_neg`, then I think the field should be too, and then I think `affect` should be the other. They would still be mutating. Is that sensible?

**Comment by ccontrer** [comment]
> If the keyword arg is affect_neg, then I think the field should be too, and then I think affect should be the other.

I agree. Or not letting `affect_neg!` be an keyword. As in 
```
ContinuousCallback(condition,affect!,affect_neg!,
                   rootfind,
                   save_positions;
                   interp_points=10,
                   abstol=1e-14,reltol=0)
ContinuousCallback(condition,affect!,
                   rootfind,
                   save_positions;
                   interp_points=10,
                   abstol=1e-14,reltol=0) = ContinuousCallback(condition,affect!,affect!,rootfind,save_positions)
```
or something like that.

**Comment by ChrisRackauckas** [comment]
I like that suggestion a lot. I think that's the correct way forward.

**Comment by ChrisRackauckas** [comment]
I implemented this suggestion. There is a depwarn telling people to look at the docs if they use the kwarg, and the docs are being updated right now. I'll tag a new version with this soon.

**Comment by ccontrer** [comment]
Funny, it looks like a previous event affects the flag of the other effect. Runing
```
f = function (t,u,du)
  du[1] = u[2]
  du[2] = -9.81
end

condtion= function (t,u,integrator) # Event when event_f(t,u,k) == 0
  u[1]
end

affect_nothing! = nothing
affect_bounce! = function (integrator)
  integrator.u[2] = -integrator.u[2]
end

interp_points = 10
rootfind = true
save_positions = (true,true)
callback = ContinuousCallback(condtion,affect_nothing!, affect_bounce!,rootfind,interp_points,save_positions,1e-14,0)

u0 = [5.0,30.0]
tspan = (0.0,7.0)
prob = ODEProblem(f,u0,tspan)

sol = solve(prob,callback=callback)
plot(sol)
```
gives
![figure_1](https://cloud.githubusercontent.com/assets/5474403/22171280/99abcae0-df47-11e6-9b1c-1fbc75d32f39.png)
But changing
```
u0 = [-5.0,30.0]
```
never calls `event_bounce!`
![figure_2](https://cloud.githubusercontent.com/assets/5474403/22171295/d1049940-df47-11e6-941e-2ad2052d4449.png)
for example if a include a `print` inside it.
