### ISSUE TITLE
Default norm for Dual numbers

### ISSUE THREAD

**Issue by MikeInnes** [JuliaDiffEq/DiffEqBase.jl#184]
RE https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/156/files

This can lead to incorrect gradients. I don't know exactly what cases it comes up in, but perhaps we can work that out and e.g. only drop when time is not dual valued. Or something else altogether; the special cases here seem like a pretty glaring code smell to me, and presumably cause issues for other packages too.

What are the costs of removing that default? Just that time must be dual valued? Since we already have to convert `u0` etc by hand I would argue this convenience isn't worth sacrificing correctness.

**Comment by ChrisRackauckas** [comment]
Using duals on time is quite uncommon. But we should probably add the time-type to the norm so it can appropriately dispatch. That is a huge change though.

**Comment by MikeInnes** [comment]
Summarising a slack discussion: We probably need to overload something like `unsafe_convert(T, x)` as a way of saying "trust me, I know what I'm doing here" to forwarddiff (but without an explicit dependency). That would at least solve the problem when `t` is Dual, and we know that the derivatives will cancel out somehow.

**Comment by MikeInnes** [comment]
I take it you've implemented the fix for when time is explicitly dual valued, but still drop partials when time is a float?

If so then this issue still applies, since users will get incorrect gradients in some cases.

**Comment by ChrisRackauckas** [comment]
what's a case where they get an incorrect gradient?

**Comment by MikeInnes** [comment]
I don't have a specifically constructed example, but the motivation for this issue was a case where we had an adaptive solver + a continuous event. We can now at least work around the issue by making time dual valued, but IIUC we'd still have gotten bad gradients in the first place.

**Comment by ChrisRackauckas** [comment]
Doesn't that error?

**Comment by MikeInnes** [comment]
You tell me; my understanding of your proposed fix is that you're passing the time type to the default norm, so that what would otherwise error instead silently converts `Dual` to `typeof(t)`. The error is the behaviour I'd like to have though.

I'll try and figure out an MRE.

**Comment by ChrisRackauckas** [comment]
Yes, it'll work in the non callback case. But in the callback case, there is a link between time and state in the rootfinding, and this will error if time isn't dual. So it seems like that should be correct?

**Comment by MikeInnes** [comment]
Ah OK, I was not up to date on your thinking here. In that case, yes, that makes me very happy :+1:
