### ISSUE TITLE
maxiters warnings with fixed step methods

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/DiffEqBase.jl#188]
```
model1 = @reaction_network rn begin
    (5,5000), X ↔ 0
end
prob1 = SDEProblem(model1,[1000.],(0.,200.))
sol1 = solve(prob1, EM(), dt = 0.0001)
```

gives 
```
┌ Warning: Interrupted. Larger maxiters is needed.
└ @ DiffEqBase ~/.julia/dev/DiffEqBase/src/integrator_interface.jl:150
```

Should `maxiters` have been automatically increased to allow for the passed in `dt`? `Euler` with an `ODEProblem` also gives a similar warning.

**Comment by ChrisRackauckas** [comment]
it should be `adaptive == true && iter >= maxiters`. That would fix this.

**Comment by ChrisRackauckas** [comment]
PRs for this are in. Just doing OrdinaryDiffEq.jl and StochasticDiffEq.jl is sufficient since only the native Julia methods can trigger fixed time steps.

**Comment by isaacsas** [comment]
Thanks!
