### ISSUE TITLE
Possibilty of WilliamsonWrapper

### ISSUE THREAD

**Issue by kanav99** [JuliaDiffEq/DiffEqBase.jl#261]
I smell some similar optimization over here -
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/nlsolve/newton.jl#L140 . We can remove that `k` from the cache. Maybe we should have a common interface for all such things.

**Comment by ChrisRackauckas** [comment]
I wouldn't do it there. One array in Newton isn't a big deal like 1 array in a low-memory setting. It wouldn't work in all non-Julia codes.

**Comment by kanav99** [comment]
Yeah, if it breaks compatibility then its a no.
