### ISSUE TITLE
Conversion and Promotion of Problems

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#28]
Continuing from https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/1 , we have the types, we just need conversions and promotions. The conversions are mostly trivial, except @mauro3 found that handling the Jacobians is non-trivial. We should work to get everything except the Jacobians working first, then go back to working on those.

**Comment by mauro3** [comment]
@ChrisRackauckas, I don't think I'll find time to spend on this in the near future, sorry!

**Comment by ChrisRackauckas** [comment]
Thanks for the update! Your code will at least be a good starting point.

**Comment by ChrisRackauckas** [comment]
Handling this in a different way.
