### ISSUE TITLE
Linear Operator Types

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#29]
We need to create linear operator types which will act like matrices `M*u` but also have a call `M(t,u)=M*u` so that way they can be used in place of functions. The general interface should be comparable to `LinearMap`. Concrete types would be akin to one like a `FunctionMap`, but then also ones that can represent things like the operator for the upwind-scheme, or non-constant mass matrices.

**Comment by aytekinar** [comment]
What is the status of this issue? How would you like to have this one?

**Comment by ChrisRackauckas** [comment]
This is related to @shivin9 's GSoC project. The other mentor on it is @dextorious. You can find the WIP repo at:

https://github.com/shivin9/PDEOperators.jl

Right now there's generation of finite difference operators of arbitrary order and arbitrary derivatives on equally spaced grids. We're going to build up that set of operators and have that guide the development of the design.

I'm not sure what in full is needed. I know that the function call syntax needs to be added in order for auto-conversion to work. But also, there needs to be direct access to the operator. You can see that I have exponential RK and IIF methods implemented:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/exponential_rk_integrators.jl
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/iif_integrators.jl

and these use the direct access to the operator. However, they do `A = f(t,u,du)`, as in, the function call return the operator. Something like this would also need to be possible, i.e. return the operator given time and `u`, since that's how we can specify mass matrices which change in space and time. So what we see is then a few things. For an operator `A`, we need to be able to do:

1) Direct access to the operator to do `A*u`, `full(A)`, `sparse_full(A)`, `expm(A)`, `expmv(A)`, etc.
2) Function call: `A(t,u,du)` for inplace and `du = A(t,u)` for out-of-place, meaning `A*u` and `A_mul_B!`.
3) If the operator is not a constant, update it with `(t,u)`. Right now, this is ad-hocly implemented in the integrators as `A = A(t,u,du)` and directly contradicts the interface of point 2 and is just weird. But there should be a mutating form, i.e. `update_coefficients!(A,t,u)` that changes the internal coefficients somehow, and a out-of-place form `B = update_coefficients(A,t,u)` to handle immutable operators which may change.
4) The interface needs some type information for whether the operator is constant or not.
5) The interface needs to designate things like if it's diagonal or symmetric. It needs to be able to denote if a special exponential operator exists.
6) It needs to be compatible with tools like IterativeSolvers.jl and `\`.

Given what I ran into with IIF + exponential RK, I believe those are all of the requirements on the interface.

**Comment by aytekinar** [comment]
Thank you for all the help and explanation. I was interested because some of the functionality in `LinearMap` and those you have listed are coinciding with our linear system abstractions. I just wanted to see if we can benefit from each other, but yours is a different set of needs in the end.

**Comment by ChrisRackauckas** [comment]
>I just wanted to see if we can benefit from each other, but yours is a different set of needs in the end.

Out of curiosity, what kind of type are you creating?

**Comment by ChrisRackauckas** [comment]
AbstractDiffEqOperator interface

1. Function call and multiplication: A(t,u,du) for inplace and du = A(t,u) for
   out-of-place, meaning A*u and A_mul_B!.
2. If the operator is not a constant, update it with (t,u). A mutating form, i.e.
   update_coefficients!(A,t,u) that changes the internal coefficients, and a
   out-of-place form B = update_coefficients(A,t,u).
3. is_constant(A) trait for whether the operator is constant or not.
4. diagonal, symmetric, etc traits from LinearMaps.jl.
5. Optional: expm(A). Required for simple exponential integration.
6. Optional: expmv(A,t,u) = expm(t*A)*u and expmv!(v,A::DiffEqOperator,t,u)
   Required for sparse-saving exponential integration.
7. Optional: factorizations. A_ldiv_B, factorize et. al. This is only required
   for algorithms which use the factorization of the operator (Crank-Nicholson),
   and only for when the default linear solve is used.

PDEOperators.jl will change over to `AbstractDiffEqOperator{T}` and match this.
