### ISSUE TITLE
`ODEProblem`: Check whether `tType` is `Any`

### ISSUE THREAD

**Issue by ranocha** [JuliaDiffEq/DiffEqBase.jl#30]
I've encountered some strange error messages if `tType == Any` in `ODEProblem`:

```
julia> using DifferentialEquations
julia> f(t,u) = u
julia> prob1 = ODEProblem(f, u0, (0.,1))
julia> solve(prob1)
ERROR: MethodError: no method matching OrdinaryDiffEq.DEOptions{uEltype,uEltypeNoUnits,tTypeNoUnits,tType,F2,F3,F4,F5,F6,tstopsType,ECType,SType}(::Int64, ::Int64, ::Bool, ::Bool, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Rational{Int64}, ::OrdinaryDiffEq.#ODE_DEFAULT_NORM, ::Void, ::DataStructures.BinaryHeap{Any,DataStructures.LessThan}, ::DataStructures.BinaryHeap{Any,DataStructures.LessThan}, ::DataStructures.BinaryHeap{Any,DataStructures.LessThan}, ::Void, ::Bool, ::Int64, ::String, ::OrdinaryDiffEq.#ODE_DEFAULT_PROG_MESSAGE, ::Bool, ::Bool, ::Float64, ::Float64, ::Float64, ::Bool, ::Bool, ::DiffEqBase.CallbackSet{Tuple{},Tuple{}}, ::OrdinaryDiffEq.#ODE_DEFAULT_ISOUTOFDOMAIN, ::OrdinaryDiffEq.#ODE_DEFAULT_UNSTABLE_CHECK, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool)
Closest candidates are: ...
```

```
julia> using DifferentialEquations
julia> f(t,u) = u
julia> prob2 = ODEProblem(f, u0, (0,1.))
julia> solve(prob2)
ERROR: InexactError()
 in convert at ./rational.jl:68 [inlined]
 in Int64(::Rational{Int64}) at ./sysimg.jl:53
 in #init#45(::Int64, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Void, ::Bool, ::Void, ::Bool, ::Bool, ::Bool, ::Int64, ::Bool, ::Rational{Int64}, ::Rational{Int64}, ::Rational{Int64}, ::Int64, ::Rational{Int64}, ::Rational{Int64}, ::Bool, ::Rational{Int64}, ::Rational{Int64}, ::Int64, ::Float64, ::Rational{Int64}, ::OrdinaryDiffEq.#ODE_DEFAULT_NORM, ::OrdinaryDiffEq.#ODE_DEFAULT_ISOUTOFDOMAIN, ::OrdinaryDiffEq.#ODE_DEFAULT_UNSTABLE_CHECK, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::String, ::OrdinaryDiffEq.#ODE_DEFAULT_PROG_MESSAGE, ::Void, ::DiffEqBase.CallbackSet{Tuple{},Tuple{}}, ::Bool, ::Bool, ::Array{Any,1}, ::DiffEqBase.#init, ::DiffEqBase.ODEProblem{Float64,Any,false,#f,DiffEqBase.CallbackSet{Tuple{},Tuple{}}}, ::OrdinaryDiffEq.Tsit5, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at ...
```

Since these errors occur not in the construction of the `ODEProblem` but in `solve`, it took me some time to fix it. Thus, it might make sense to test whether `tType == Any` in `ODEProblem`. I could start implement such tests in the constructors in `ode_problems.jl`.

We might at least want to print some warnings if `tType == Any`.

**Comment by ChrisRackauckas** [comment]
I thought this would've been caught since the tuple needs to match types. Yes, a better warning here would be good.

**Comment by ranocha** [comment]
The problem is that `tType` becomes `Any` in undesired cases. I will write a few warnings.

**Comment by ChrisRackauckas** [comment]
I didn't think tuples would convert like that.

**Comment by ranocha** [comment]
I think the tuple itself is not converted but the call to `eltype` returns `Any`.

**Comment by ChrisRackauckas** [comment]
Oh I see. It shouldn't promote. Should probably use `typeof(tspan[1])` so that way it throws an error if the types don't match

**Comment by ranocha** [comment]
Maybe it would be better to use `promote_type(map(typeof, tspan)...)`? This would be the desired solution in most cases and doesn't print an error.

**Comment by ChrisRackauckas** [comment]
That sounds good.

**Comment by ranocha** [comment]
Okay, I'll implement this version for the problems.

**Comment by ChrisRackauckas** [comment]
Okay cool. Master might be a little wonky right now because we've been building up a bunch of breaking changes for the DiffEq 2.0 release. It's okay if tests don't pass.

**Comment by ranocha** [comment]
Okay, I've just checked out master and got `ERROR: LoadError: LoadError: UndefVarError: ArrayPartition not defined`. I'll ignore that.
