### ISSUE TITLE
`DEDataArray` needs `convert` method for not-in-place dynamics

### ISSUE THREAD

**Issue by goretkin** [JuliaDiffEq/DiffEqBase.jl#327]
```julia
using DifferentialEquations

struct SimulationState{T,U} <: DifferentialEquations.DEDataArray{T, 1}
    x::Vector{T}
    u::U
end 

#function Base.convert(::Type{SimulationState{T, U}}, a::AbstractArray{T}) where {T,U}
#    SimulationState(a, zero(eltype(a)))
#end

function open_loop(state, parameters, time)
    v = state[1] * -0.1 + state.u
    return [v]
end

initial_conditions = SimulationState([10.0], 0.0)
time_span = (0.0, 20.0)
ode_prob = ODEProblem(open_loop, initial_conditions, time_span, nothing)

sol = solve(ode_prob, Tsit5(), reltol=1e-8, abstol=1e-8)
```

gives

```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type SimulationState{Float64,Float64}
```

on line https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/aa319007e6a21a0f0534ac793ea1897f1a85b6ee/src/perform_step/low_order_rk_perform_step.jl#L608

Any vector operations on a `DEDataArray` turns it back into an `Array`, and then the solvers try to assign an `Array` into a `DEDataArray` field.

Perhaps this doesn't happen with the in-place methods (though I'm not sure why it wouldn't), but I don't know how to do that with the `DEDataArray`, either.

Apologies if I posted this on the wrong issue tracker.

**Comment by goretkin** [comment]
The mutating version works fine for me, however:

```julia
import OrdinaryDiffEq: DEDataArray, ODEProblem, solve, Tsit5

mutable struct SimulationState{T,U} <: DEDataArray{T, 1}
    x::Vector{T}
    u::U
end 

function open_loop!(dstate, state, parameters, time)
    v = state[1] * -0.1 + state.u
    dstate[1] = v
end


initial_conditions = SimulationState([10.0], 0.0)
time_span = (0.0, 20.0)
ode_prob = ODEProblem(open_loop!, initial_conditions, time_span, nothing)

sol = solve(ode_prob, Tsit5())
```

I had to change the `SimulationState` to be mutable (which is clear from the example in the documentation), but I'm not sure why the solvers rely on mutating it.

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/test/downstream/data_array_regression_tests.jl for a corrected example.
