### ISSUE TITLE
recursivecopy! for sparse types

### ISSUE THREAD

**Issue by jebej** [JuliaDiffEq/DiffEqBase.jl#34]
I was trying to use a sparse `u` (and `du`) but the solver fails due to a lack of `recursivecopy!` method for sparse vectors. Is there an issue with supporting sparse objects?

**Comment by ChrisRackauckas** [comment]
There is no issue for it. But this should be handled with a `recursivecopy!` dispatch in RecursiveArrayTools.jl

**Comment by jebej** [comment]
Got it, should I close the issue here?

**Comment by ChrisRackauckas** [comment]
Yeah. Can you open it in RecursiveArrayTools.jl with an example?
