### ISSUE TITLE
Axis labels when using `0` in `vars`

### ISSUE THREAD

**Issue by aytekinar** [JuliaDiffEq/DiffEqBase.jl#35]
### Description

When using plotting functionality with `vars` keyword, the recipe recognizes the use of the (independent) time variable `t` and labels the x-axis properly. However, when the place of the time variable is switched, the recipe cannot recognize it anymore.

Not sure if such a behaviour should be needed, but there is this minor inconsistency.

### Actual Behaviour

```julia
using DiffEqBase, OrdinaryDiffEq
using Plots
gr()

f(t,x,dx) = (dx[1] = -x[1]; nothing)
prob = ODEProblem(f, [1.], (0.,10.))
sln = solve(prob, Tsit5())

plot(sln, vars=[(0,1)]) # plots x[1] vs t, having x-label as `t`
plot(sln, vars=[(1,0)]) # changes the axes of above; but no `y-label` as `t`
```

### Desired Behaviour

```julia
using DiffEqBase, OrdinaryDiffEq
using Plots
gr()

f(t,x,dx) = (dx[1] = -x[1]; nothing)
prob = ODEProblem(f, [1.], (0.,10.))
sln = solve(prob, Tsit5())

plot(sln, vars=[(0,1)]) # plots x[1] vs t, having x-label as `t`
plot(sln, vars=[(1,0)]) # changes the axes of above; AND `y-label` as `t`
```

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/1e2f6a9e0b2a811df62125f1aed3e159aa971f28
