### ISSUE TITLE
Solution Plotting Recipe - Default linewidth

### ISSUE THREAD

**Issue by gileshd** [JuliaDiffEq/DiffEqBase.jl#425]
Within the solution plotting recipe the linewidth is set to 3:
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/34ce600793b2b3d8865ebae925ec2a6640f7d952/src/solutions/solution_interface.jl#L81

By setting the default linewidth within the recipe it prevents users from interacting with the default value using PlotThemes.jl.

It seems slightly strange to impose this default, and it is inconvenient that it prevents users from using `theme()` to change the default within a script.

**Comment by ChrisRackauckas** [comment]
Interesting point. Maybe the right thing would be to make the default linewidth larger in the default Plots theme. I'd accept a PR getting rid of this here.

**Comment by gileshd** [comment]
Sorry to clarify you would accept a PR just removing the `linewidth --> 3` in the plot recipe?

**Comment by ChrisRackauckas** [comment]
yes
