### ISSUE TITLE
Incorrect compatibility bounds on DiffEqBase 6.22.2 and 6.23

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaDiffEq/DiffEqBase.jl#462]
Recently we've been getting some errors in `Manifolds.jl` tests on Julia 1.0, like this (with DiffEqBase 6.22.2): https://travis-ci.org/github/JuliaNLSolvers/Manifolds.jl/jobs/663616477?utm_medium=notification&utm_source=github_status or this (with DiffEqBase 6.23): https://travis-ci.org/github/JuliaNLSolvers/Manifolds.jl/jobs/663588022?utm_medium=notification&utm_source=github_status . Both versions are clearly not compatible with Julia 1.0 but in the registry they are advertise as compatible. Could you fix this?

**Comment by ChrisRackauckas** [comment]
> Both versions are clearly not compatible with Julia 1.0 but in the registry they are advertise as compatible

It's not so clear... on DiffEqBase.jl v6.23, it does:

```julia
julia> using Compat

julia> eachcol
eachcol (generic function with 1 method)
```

do you have a bound on Compat and was this added in a point release?

**Comment by ChrisRackauckas** [comment]
Since something weird is going on with Compat, I'l just up the bound rather than trying to fuss with it too much, so see the General PR.

**Comment by mateuszbaran** [comment]
I have Compat set to 3.8 in the Manifest file and nothing complains about it. Maybe your change in the registry will be enough.

**Comment by ChrisRackauckas** [comment]
The change to the registry will just change the bounds, which shouldn't be needed on 6.23, but is a heavy-handed fix because Compat doesn't seem to be working here.

**Comment by ChrisRackauckas** [comment]
The bounds should be good now. Let me know if you have any more issues.

**Comment by mateuszbaran** [comment]
Thanks, it works now 🙂 .
