### ISSUE TITLE
`numargs` fails for a function with explicit generic (and constrained) arguments

### ISSUE THREAD

**Issue by mobius-eng** [JuliaDiffEq/DiffEqBase.jl#55]
I have a function with explicitly stated constrained generic arguments:

```julia
function equation!{T<:Real, U <:AbstractUnsaturatedModel{T}, V <: Inlet{T}}(t :: T, s :: Vector{T}, d :: Darcy{T,U,V}, Ds :: Vector{T})
```

Creating a parameterized function as

```julia
ParameterizedFunction(equation!, d)
```
Results in error in `numargs` (`utils.jl`) function that seems unable to calculate correctly the number of arguments of such a generic function. The problem is in the call

```julia
m.sig.parameters
```

where `m` is a method of `equation!`: there is no field `parameters` for my function.

For something simpler it works:

```julia
function lz(t, u, du)
	σ = 10.0
	ρ = 28.0
	β = 8/3.0
	du[1] = σ*(u[2]-u[1])
	du[2] = u[1]*(ρ-u[3]) - u[2]
	du[3] = u[1]*u[2] - β*u[3]
end

first(methods(lz)).sig.parameters
```
```
svec(DarcyExample.#lz, Any, Any, Any)
```

However the change to explicit argument type results in error:

```julia
function lz1{T<:Real}(t::T, u::Vector{T}, du::Vector{T})
	σ = 10.0
	ρ = 28.0
	β = 8/3.0
	du[1] = σ*(u[2]-u[1])
	du[2] = u[1]*(ρ-u[3]) - u[2]
	du[3] = u[1]*u[2] - β*u[3]
end

first(methods(lz1)).sig.parameters
```

```
type UnionAll has no field parameters
```

**Comment by ChrisRackauckas** [comment]
Huh, thanks for catching this. I am not currently aware of a solution though... you can pass `iip = true` as a keyword arg to fix this though. That'll change with https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/51 to a different syntax `ODEProblem{true}(f,u0,tspan)`, but hopefully a better fix for this can be found.

@ScottPJones do you know how to handle this at all?

**Comment by mauro3** [comment]
x-refs:
https://github.com/JuliaLang/julia/pull/22687
https://github.com/JuliaLang/julia/issues/22051

**Comment by ChrisRackauckas** [comment]
Ahh yes, thanks @mauro3. Just noticed

```julia 
julia> first(methods(lz1)).sig
Tuple{#lz1,T,Array{T,1},Array{T,1}} where T<:Real

julia> typeof(first(methods(lz1)).sig)
UnionAll
```

`UnionAll` means it was introduced in v0.6, and so I assume that https://github.com/JuliaLang/julia/pull/22687 is precisely what we need. Hmm, I am not sure if there's a good v0.6 workaround. 

```julia
julia> fieldnames(first(methods(lz1)).sig)
2-element Array{Int64,1}:
 1
 2

julia> first(methods(lz1)).sig
Tuple{#lz1,T,Array{T,1},Array{T,1}} where T<:Real

julia> first(methods(lz1)).sig.1
ERROR: syntax: extra token "0.1" after end of expression

julia> first(methods(lz1)).sig.2
ERROR: syntax: extra token "0.2" after end of expression
```

It seems rather peculiar.

**Comment by ChrisRackauckas** [comment]
I think that means https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/51 plus https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/52 is likely a good intermediate fix, and this issue then fixes itself on v0.7/v1.0 unless we find someone who knows a hack around it.

**Comment by mobius-eng** [comment]
@ChrisRackauckas I am on the master branch of `DifferentialEquations.jl` and `ODEProblem` does accept `iip=true` but `ParameterizedFunction` doesn't:

```julia
function lz(t, u, p, du)
	σ, ρ, β = p
	du[1] = σ*(u[2]-u[1])
	du[2] = u[1]*(ρ-u[3]) - u[2]
	du[3] = u[1]*u[2] - β*u[3]
end

flz = ParameterizedFunction(lz, (10.0, 28.0, 8/3.0),iip=true)
```

```
MethodError: no method matching DiffEqBase.ParameterizedFunction(::DarcyExample.#lz, ::Tuple{Float64,Float64,Float64}; iip=true)
Closest candidates are:
  DiffEqBase.ParameterizedFunction(::Any, ::Any) at /home/alexey/.julia/v0.6/DiffEqBase/src/constructed_parameterized_functions.jl:7 got unsupported keyword argument "iip"
```

and the error with the elaborate typing happens, in this case, at the call to `ParameterizedFunction`.

**Comment by ChrisRackauckas** [comment]
I see. That part wasn't exposed. Try master now: https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/e6a5b02f49840dc419f9d2664a823b8a12a2c546 . I'll add this to the things which will be affected by https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/51

**Comment by ChrisRackauckas** [comment]
Just confirmed that the latest example works on DiffEqBase master. So you can manually add `iip` to fix. As for the general case on v0.6, we should probably take this to Discourse to see if anyone has a v0.6 workaround for the auto-detection.

**Comment by ChrisRackauckas** [comment]
@mobius-eng note that on the current DiffEqBase.jl that syntax changes to:

```julia
flz = ParameterizedFunction{true}(lz, (10.0, 28.0, 8/3.0))
```

All of the constructors which have to deal with inplace vs not-in-place have this setup now. It'll get documented ASAP. The advantage is that this is an inferrable way to specify it. 

Additionally,

```julia
length(Base.unwrap_unionall(Tuple{T,T,T2} where {T,T2}).parameters)
```

works. So that means

```julia
length(Base.unwrap_unionall(first(methods(lz1)).sig).parameters)
```

will work for your case. Using this your original issue is now fixed on master.

```julia
function equation!{T<:Real, U , V}(t:: T, s :: Vector{T}, d :: U, Ds :: Vector{V}) end
ParameterizedFunction(equation!, [0.5])
```

I'll tag this soon.
