### ISSUE TITLE
Add reinit to the integrator interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#58]
`reinit` would set the problem back to the initial condition and `tspan[1]`. This would be a great way to cheaply resolve with different parameters. Also, since one can change `integrator.prob.u0` and `integrator.prob.tspan`, this would be a great way to solve with slightly different setups but reuse the internal caches.

**Comment by ChrisRackauckas** [comment]
@Datseris had a good idea that we should probably allow choices here, so I would think the signature should be:

```julia
reinit(integrator::DEIntegrator,u0 = integrator.sol.prob.u0, t0 = integrator.sol.prob.tspan[1], erase_sol = true)
```

Comments?

**Comment by Datseris** [comment]
This is in-place ore returns a new Integgrator?

**Comment by ChrisRackauckas** [comment]
In-place. Should also have a `copy` version for what you want?

**Comment by ChrisRackauckas** [comment]
This has been implemented for OrdinaryDiffEq. StochasticDiffeq and DelayDiffEq will need a few tweaks.

**Comment by Datseris** [comment]
Is this in an open PR? I would like to see the code just to get the hang of the function signature, since I will be probably using it the moment it comes out!

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/218

**Comment by ChrisRackauckas** [comment]
This can now be finished in the respective PRs
