### ISSUE TITLE
problem_new_parameters doesn't pass keyword arguments

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#62]
This means that parameter estimation won't pass on keyword arguments that are in the solver. This isn't good.

**Comment by devmotion** [comment]
Do you mean other problem fields besides `u0` and `tspan`, such as `mass_matrix`, `callback`, and `problem_type` for `ODEProblem`? According to https://github.com/JuliaDiffEq/DiffEqParamEstim.jl/blob/master/src/build_loss_objective.jl#L21 (and similar lines) additional solver options should be applied in every step.

However, I worry about lines like
https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/parameters_interface.jl#L21-L23
Shouldn't that immediately fail for units? And it seems a bit strange to enforce the same units for `t` and `u`. Are these type changes really necessary?

**Comment by ChrisRackauckas** [comment]
>Shouldn't that immediately fail for units? And it seems a bit strange to enforce the same units for t and u. Are these type changes really necessary?

It's necessary if you want to autodifferentiate through the full ODE solver. This occurs when using local optimizers for parameter estimation. In the future that can get replaced with sensitivity equations, in which case this won't be an issue. But yes, this will cause units to fail in this case, but I am not sure how to solve that.

>Do you mean other problem fields besides u0 and tspan, such as mass_matrix, callback, and problem_type for ODEProblem?

Yeah. Since it's written out by hand, some of them are missing some keyword arguments. In most of those cases, there's a not a solver which uses it yet, like `mass_matrix` for `SDEProblem`. But it should be noted that it is incorrect.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/c5c640ce63fd1a00d34568af003c836f7822ce75
