### ISSUE TITLE
don't override display

### ISSUE THREAD

**Issue by stevengj** [JuliaDiffEq/DiffEqBase.jl#71]
You are overloading `display` in order to customize output.  This is the wrong way to do it — see the manual on [custom pretty printing](https://docs.julialang.org/en/release-0.6/manual/types/#Custom-pretty-printing-1).

To customize REPL output, you should override `Base.show(io::IO, x::MyType)` and/or `Base.show(io::IO, ::MIME"text/plain", x::MyType)`, as explained in the manual.

Overriding `display` directly will break IJulia, Juno, and other environments that have a custom `display` mechanism.

**Comment by stevengj** [comment]
Similarly in DiffEqJump, DiffEqPDEBase

**Comment by ChrisRackauckas** [comment]
Thanks for the information! Implemented in each package.

**Comment by stevengj** [comment]
Is it fixed?  I'm still seeing lots of cases like [this](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/4804cc98b14eceb806879c36bef8b0ad0868a229/src/problems/problem_traits.jl#L50-L57)

**Comment by ChrisRackauckas** [comment]
Interesting. I did I search via Atom and thought I got them all...

**Comment by stevengj** [comment]
(Note also that `display` never takes an `IO` argument, so overriding `Base.display(::IO, x)` seems useless as well as wrong.)

**Comment by stevengj** [comment]
I just looked for `display` on Github.

**Comment by ChrisRackauckas** [comment]
Thanks. That was much more efficient.

**Comment by stevengj** [comment]
See also my comments on your commits for further problems.

(I can't believe that Julia went until 2016 to [document how to do this](JuliaLang/julia/pull/18634) … in the meantime, people have done all sorts of half-broken things in the packages.  Further improvements to the documentation are welcome.)

**Comment by ChrisRackauckas** [comment]
Thanks. I think I got it all. Never knew about the docs, probably because I poked around to find a way that "worked" before the docs on it were written...
