### ISSUE TITLE
Should problem types be immutable?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#73]
If problem types were immutable, it would be free to make them. Is there ever a good reason to mutate them? Adding new callbacks or anything like that isn't possible because that changes the typing and it's strictly typed. If the `u0` is mutable you can already just mutate that, but in many cases you want to change the type so instead creating a new object is really what's the right way to do it. `tspan` is a tuple so it can't be modified, and neither can the function. So I am not sure if the mutability is even useful.

Does anyone use the mutability of the problem type? @Datseris @devmotion @ranocha

**Comment by Datseris** [comment]
Thank you for tagging me here and even asking for my opinion. 

I just scanned my source code: I do not mutate any `ODEProblems`.

In fact, for me it would be better if the type was immutable!

**Comment by ranocha** [comment]
I don't mutate the problems either. Thanks for asking.

**Comment by devmotion** [comment]
I had a look at my code, and it seems I don't mutate problems. Hence immutable problems are fine with me.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/74

Is there a reason for the solution types to be mutable other than the fact that the solvers change the retcode internally and animations mutate `tslocation`?

**Comment by Datseris** [comment]
isn't the fact that solutions are mutable that makes `Integrator` be able to have a `sol` type?

**Comment by ChrisRackauckas** [comment]
No, because the integrator usually modifies things like `sol.u`, which can be modified even if `sol` was immutable. That's why I am wondering if it really needs to be mutable. The only two fields I know are mutated are things that aren't parametrically-typed (`Int` and `Symbol`), so in that case I think `sol` could be immutable as well and those cases where one modifies the retcode, it could just return a new `sol` if it's basically free. That would be unless anyone has done something like `sol.t = ...`, but it's been over a year now and I don't think I've seen a single code do something like that?

**Comment by Datseris** [comment]
Not me for sure. I leave all handling of `sol` to DiffEq and only get the `sol.u` field.

**Comment by ChrisRackauckas** [comment]
I'm sure almost any case of modifying it would break everything?

**Comment by ChrisRackauckas** [comment]
No changes to the ecosystem were required at all to change to immutable problems (just a few tests where I changed the direction of time and stuff like that, easy fixes and definitely not a normal use case).

I am going to change the solution types as well.

**Comment by ChrisRackauckas** [comment]
solution and problem types are immutable. Essentially nothing broke.
