### ISSUE TITLE
Timesteps API for fixed timestep methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBase.jl#8]
I think it would be reasonable to document an advanced timestepping method for fixed timestep methods as follows:

- If `dt` is chosen, every step will be of size `dt` unless in the interval there is a value of `tstops`, which it will then walk to that value
- If `dt` is not chosen and `tstops` is empty, automatic choice of `dt` will occur
- If `dt` is not chosen and `tstops` is not empty, the algorithm will walk to each value of `tstops`

@mauro3 does that make sense? This would use the `tstops` vector instead of special casing `dt` into a vector for this case.

**Comment by mauro3** [comment]
Sounds good, except that the automatic choice of `dt` might be beyond what a fixed step solver could reasonably provide.  Maybe better error?

**Comment by ChrisRackauckas** [comment]
>Maybe better error?

Maybe. Last night I was playing with the SDE solvers a bit an the automatic choices, having to be conservative, were pretty bad for fixed timestep methods. I thought there was a bug before I realized it was just a bad automatic choice (which then didn't get fixed through adaptivity). 

But sometimes it's helpful. Maybe I can expose the Gladwell & Shampine method somewhere else since it's so commonly used. But it is inherently conservative so it doesn't do too well for fixed timestep methods.

**Comment by mauro3** [comment]
I think using a fixed step solver just necessitates thinking about the time step.  So an error when not providing one seems fine.

**Comment by ChrisRackauckas** [comment]
Implemented in OrdinaryDiffEq with the request changes, and this has been noted in the docs.
