### ISSUE TITLE
disable update warning

### ISSUE THREAD

**Issue by tpapp** [JuliaDiffEq/DiffEqBase.jl#94]
Would it be possible to opt-out from the [update warning](https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/d462ecf0f5d10271358d6ee7312277a2efd5968a/deps/build.jl) once I have seen it?

I have to admit that I don't have a suggestion for the implementation though. Eg by setting an environment variable?

**Comment by mauro3** [comment]
I once put this:
https://github.com/mauro3/Parameters.jl/commit/56d57f4613a349266d286d9925356effad7a024e#diff-ec1155cc07b8ae5fc6787c9cb23a7986
into Parameters.jl, which only printed during precompile.  Maybe that still works?

**Comment by tpapp** [comment]
Wouldn't it just show up at a different time, instead of at `Pkg.update()`?

**Comment by mauro3** [comment]
It showed up every time Parameters.jl got recompiled.  Thus it can show up several times but not every time one used Parameters.jl.  I thought it was ok signal to noise ratio.

**Comment by tpapp** [comment]
It is not a big deal either way. But this could be a good opportunity to work towards a general mechanism, unless `Pkg3` already supports something like this.

**Comment by ChrisRackauckas** [comment]
I don't know how to make an opt-out easily, so I opened an issue for this to be Pkg3 and I think I want to leave it up for 6 months. The upgrade has been surprisingly smooth and I think blasting the warning had a part in that, though it was a little noisy.
