### ISSUE TITLE
Use logspace instead of linspace in plotting recipe when appropriate

### ISSUE THREAD

**Issue by non-Jedi** [JuliaDiffEq/DiffEqBase.jl#95]
If `xscale` is set to e.g. `:log10`, `logspace` should be used instead of
`linspace`. This is necessary for visualizing the example from the DAE tutorial
well (https://github.com/JuliaDiffEq/DiffEqDocs.jl/pull/113).

**Comment by ChrisRackauckas** [comment]
Thanks for the issue. Yes, this was completely overlooked.
